name: Test Build

on:
  push:
    paths: '.github/workflows/*.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PraxisCORE
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/praxiscore
          path: praxiscore
      - name: Checkout PraxisLIVE
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          path: praxislive
      - name: Setup JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build PraxisCORE
        run: mvn -B -U -f praxiscore/ install
      - name: Build PraxisLIVE
        run: mvn -B -U -f praxislive/ verify
      - name: Upload Dev build
        uses: actions/upload-artifact@v4
        with:
          name: dev-build
          path: praxislive/application/target/PraxisLIVE-*.zip
          retention-days: 7
          if-no-files-found: error
